 DELETE http://localhost:3001/api/persons/12
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Dany Mauricioss hernaandez",
   "number": "093-334-3434"
}
###
PUT http://localhost:3001/api/persons/6a37ef0dc409c98c078d11a5
Content-Type: application/json

{  
   "name": "Da",
   "number": "093-334-3434"
}
###
get http://localhost:3001/api/persons
