 DELETE http://localhost:3001/api/persons/12
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Dany Mauricioss hernaandez",
   "number": "093-334-3434"
}
###
get http://localhost:3001/api/persons
